### ISSUE TITLE
Users can select walls to add a door into it and define door location

### ISSUE THREAD

**Issue by Josh-Danks** [jopokemine/memory-palace#27]

**Comment by Josh-Danks** [comment]
- [ ] Rooms need to be selectable and display context menu and room dimensions
- [ ] Context menu to resize room
- [ ] Add bluetooth device
- [ ] Add door
- [ ] Rooms that are adjacent with a door are recognised and snap

**Comment by GenericGitHubProfile** [comment]
Bug: Internal GameObject name for room array position, i.e. Room-0, no longer being stated
Additionally, room now occasionally has first point in bottom left corner, despite cursor not going near it

**Comment by Josh-Danks** [comment]
-Potential blockers: how grid is being implemented IPF-22

**Comment by GenericGitHubProfile** [comment]
Fixed Bug:
- Resizing through context menu resulted in room being far too large, this was due to real world units (0.5-10 metres) being scaled into pixel units (100px - 2000px) twice

**Comment by GenericGitHubProfile** [comment]
wontfix: Development of Watson API integration took priority, as such this was not finished
